config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root :to => 'links#index'

  resources :links do
    resources :comments
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :link

  validates :body, :presence => true
end

app/models/link.rb
class Link < ActiveRecord::Base
  has_many :comments
  validates :headline, :presence => true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def new
    @link = Link.find(params[:link_id])
    @comment = @link.comments.new
  end

  def create
    @link = Link.find(params[:link_id])
    @comment = @link.comments.new(comment_params)
    if @comment.save
      redirect_to link_path(@comment.link)
    else
      render :new
    end
  end

  def edit
    @link = Link.find(params[:link_id])
    @comment = Comment.find(params[:id])
  end

  def update
    @comment = Comment.find(params[:id])
    if @comment.update(comment_params)
      redirect_to link_comment_path
    else
      render :edit
    end
  end

  def destroy
    comment = Comment.find(params[:id])
    comment.destroy
    redirect_to link_comment_path
  end

  private
  def comment_params
    params.require(:comment).permit(:body)
  end
end

app/controllers/links_controller.rb
class LinksController < ApplicationController
  def index
    @links = Link.all
  end

  def show
    @link = Link.find(params[:id])
  end

  def new
    @link = Link.new
  end

  def create
    @link = Link.new(link_params)
    if @link.save
      flash[:notice] = "Link successfully added"
      redirect_to links_path
    else
      render :new
    end
  end

  def edit
    @link = Link.find(params[:id])
  end

  def update
  @link = Link.find(params[:id])
  if @link.update(link_params)
    flash[:notice] = "Updated link"
    redirect_to links_path
  else
    flash[:alert] = "Try again error occured"
    render :edit
  end
end

def destroy
  @link = Link.find(params[:id])
  @link.destroy
  redirect_to links_path
end

private
  def link_params
    params.require(:link).permit(:headline, :url)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/comments/_form.html.erb
<%= render('layouts/errors', :object => @comment) %>

<%= form_for [@link, @comment] do |f| %>
  <%= f.label :body %>
  <%= f.text_field :body %>
  <p><%= f.submit %></p>
<% end %>

app/views/comments/edit.html.erb
<h1>Edit</h1>

<%= render 'comments/form' %>

app/views/comments/new.html.erb
<h1>New comment for <%= @link.headline %></h1>

<%= render 'form' %>

app/views/layouts/_errors.html.erb
<% if object.errors.any? %>
  <h3>Please fix these errors:</h3>
  <ul>
    <% object.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
  </ul>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Hackerz</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/links/_form.html.erb
<%= render "layouts/errors", :object => @link %>

<%= form_for @link do |f| %>
  <%= f.label :headline %>
  <%= f.text_field :headline %>
  <%= f.label :url %>
  <%= f.text_field :url %>
  <%= f.submit %>
<% end %>

app/views/links/edit.html.erb
<h1>Edit Link</h1>

<%= render "links/form" %>

app/views/links/index.html.erb
<% content_for :title, "Hackerz" %>
<h1>Hackerz</h1>
<ul>
  <% @links.each do |link| %>
    <li><%= link_to link.headline, link.url %></li>
  <% end %>
</ul>

<%= link_to "New Link", new_link_path %>

app/views/links/new.html.erb
<h1>new link</h1>

<%= render "links/form" %>

app/views/links/show.html.erb
<% content_for :title, "Hackerz" %>

<h1><%= @link.headline %></h1>

<% if @link.comments.any? %>
  <h4>Here are the comments for this link</h4>
  <ul>
    <% @link.comments.each do |comment| %>
      <li>
        <%= comment.body %> |
        <%= link_to "Edit", edit_link_comment_path(@link, comment) %> |
        <%= link_to "Delete", link_comment_path(@link, comment),
          :data => {:confirm => "Are you sure?",
          :method => "delete"} %>
      </li>
    <% end %>
  </ul>
<% else %>
  <p>There are no comments yet!</p>
<% end %>

<p><%= link_to "Add a comment", new_link_comment_path(@link) %></p>
<p><%= link_to "Delete List", link_path(@link),
  :data => {:confirm => "Are you sure?",
  :method => "delete"}
%></p>

<p><%= link_to "Edit List Name", edit_link_path(@link) %></p>

<p><%= link_to "Return to Lists", links_path %></p>